controller_list:
  - name: m1n6s200
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - m1n6s200_joint_1
      - m1n6s200_joint_2
      - m1n6s200_joint_3
      - m1n6s200_joint_4
      - m1n6s200_joint_5
      - m1n6s200_joint_6
  - name: "gripper"
    action_ns: gripper_command
    type: GripperCommand
    default: true
    joints:
      - robotiq_85_left_knuckle_joint
